### PR TITLE
Add PIDF-controlled Shooter implementation

### PR DESCRIPTION
**Pull request by andrewazores**

### CODE REVIEW

**Review by ddrobner — APPROVED** [review]
Looks good. Shouldn't be merged yet though as the bangbang controller might actually be fine, with the new changes

**Comment by andrewazores** [comment]
This isn't replacing the bangbang controller though, it's adding a separate parallel PIDF implementation and logic for switching between them. The default is also set to the existing bangbang controller.

**Comment by andrewazores** [comment]
Rebased.

**Comment by ddrobner** [comment]
Looks good then

**Pull request merged**
